### ISSUE TITLE
Class 'App\Http\Controllers\Web\Braintree_PaymentMethodNonce' not found

### ISSUE THREAD

**Issue by gaurav1992** [bradleyboy/laravel-braintree#4]
Hello There,

I am using Laravel 5 and the module that i am using is oureastudios/laravel5-braintree . It seems like it is fork with this repository that's i was unable to create issue there.

Well i am using this module in one of my application and i need to generate nonce to create user and add card.While using the function ....

$result = Braintree_PaymentMethodNonce::create($token);
$nonce_token = $result->paymentMethodNonce->nonce;

I am getting Class 'App\Http\Controllers\Web\Braintree_PaymentMethodNonce' not found.

Kindly help.

Your early reply will be much appreciated.

Regard 
Gaurav

**Comment by bradleyboy** [comment]
@gaurav1992 I think you need this line:

```php
$result = Braintree_PaymentMethodNonce::create($token);
```

to be:

```php
$result = \Braintree_PaymentMethodNonce::create($token);
```

And FYI, this repo is no longer maintained. The one you are using is here: https://github.com/oureastudios/laravel5-braintree

**Comment by gaurav1992** [comment]
I apologies but i already did that and it is fixed but i am still unable to generate nonce.Can you please help me with that ?

And i am using the same repo that you suggested but there is no option to raise an issue that's why i am using this repo for issue.

Thanks
